set(SCOOP_MATURITY "EP")
set(SCOOP_DESCRIPTION "Scoop - Simple ColoR pAleTtes and mappERs")
set(SCOOP_GIT_ROOT_URL "https://gitlab-ci-token:UvK74ABtfz-HqNNatsve@gitlab.gmrv.es/gmrv/scoop.git")
set(SCOOP_PACKAGE_URL "")
set(SCOOP_CI_URL "")
set(SCOOP_CI_PNG "")
set(SCOOP_ISSUES_URL "")
