set(FIRES_MATURITY "EP")
set(FIRES_DESCRIPTION "")
set(FIRES_GIT_ROOT_URL "https://gitlab-ci-token:W8m3KeFxC7F3GCk-THnz@gitlab.vg-lab.es/retrieval/FiReS.git")
set(FIRES_PACKAGE_URL "")
set(FIRES_CI_URL "")
set(FIRES_CI_PNG "")
set(FIRES_ISSUES_URL "")
