neurolots: nlphysics::Tetrahedron Class Reference
nlphysics::Tetrahedron Class Reference
Public Member Functions
NLPHYSICS_API Tetrahedron (NodePtr node0_, NodePtr node1_, NodePtr node2_, NodePtr node3_)
Constructor.
NLPHYSICS_API ~Tetrahedron (void)
Default destructor.
NLPHYSICS_API NodePtr & node0 (void)
Method that returns the first tetrahedron node.
NLPHYSICS_API NodePtr & node1 (void)
Method that returns the second tetrahedron node.
NLPHYSICS_API NodePtr & node2 (void)
Method that returns the third tetrahedron node.
NLPHYSICS_API NodePtr & node3 (void)
Method that returns the fourth tetrahedron node.
NLPHYSICS_API Eigen::MatrixXf & b0 (void)
Method that returns the b0 matrix.
NLPHYSICS_API Eigen::MatrixXf & b1 (void)
Method that returns the b1 matrix.
NLPHYSICS_API Eigen::MatrixXf & b2 (void)
Method that returns the b2 matrix.
NLPHYSICS_API Eigen::MatrixXf & b3 (void)
Method that returns the b3 matrix.
NLPHYSICS_API float & volume (void)
Method that returns the tetrahedron volume.
NLPHYSICS_API bool face0 (void) const
Method that check and return if the 0 face of the tetrahedron is a contour face.
NLPHYSICS_API bool face1 (void) const
Method that check and return if the 1 face of the tetrahedron is a contour face.
NLPHYSICS_API bool face2 (void) const
Method that check and return if the 2 face of the tetrahedron is a contour face.
NLPHYSICS_API bool face3 (void) const
Method that check and return if the 3 face of the tetrahedron is a contour face.
Protected Attributes
NodePtr _node0
First tetrahedron node.
NodePtr _node1
Second tetrahedron node.
NodePtr _node2
Third tetrahedron node.
NodePtr _node3
Fourth tetrahedron node.
Eigen::MatrixXf _b0
b0 matrix
Eigen::MatrixXf _b1
b1 matrix
Eigen::MatrixXf _b2
b2 matrix
Eigen::MatrixXf _b3
b3 matrix
float _volume
tetraheron volume
Detailed Description
Definition at line 37 of file Tetrahedron.h.
Constructor & Destructor Documentation
NLPHYSICS_API nlphysics::Tetrahedron::Tetrahedron (NodePtr node0_, NodePtr node1_, NodePtr node2_, NodePtr node3_) inline
Constructor.
Parameters
node0_ fist tetrahedron node
node1_ second tetrahedron node
node2_ third tetrahedron node
node3_ fourth tetrahedron node
Definition at line 50 of file Tetrahedron.h.
Member Function Documentation
NLPHYSICS_API Eigen::MatrixXf& nlphysics::Tetrahedron::b0 (void) inline
Method that returns the b0 matrix.
Returns
the b0 matrix
Definition at line 99 of file Tetrahedron.h.
References _b0.
NLPHYSICS_API Eigen::MatrixXf& nlphysics::Tetrahedron::b1 (void) inline
Method that returns the b1 matrix.
Returns
the b1 matrix
Definition at line 106 of file Tetrahedron.h.
References _b1.
NLPHYSICS_API Eigen::MatrixXf& nlphysics::Tetrahedron::b2 (void) inline
Method that returns the b2 matrix.
Returns
the b2 matrix
Definition at line 113 of file Tetrahedron.h.
References _b2.
NLPHYSICS_API Eigen::MatrixXf& nlphysics::Tetrahedron::b3 (void) inline
Method that returns the b3 matrix.
Returns
the b3 matrix
Definition at line 120 of file Tetrahedron.h.
References _b3.
NLPHYSICS_API bool nlphysics::Tetrahedron::face0 (void) const inline
Method that check and return if the 0 face of the tetrahedron is a contour face.
Returns
true if the 0 face of the tetrahedron is a contour face
Definition at line 135 of file Tetrahedron.h.
References _node0, _node1, _node2, and nlphysics::Node::contour().
NLPHYSICS_API bool nlphysics::Tetrahedron::face1 (void) const inline
Method that check and return if the 1 face of the tetrahedron is a contour face.
Returns
true if the 1 face of the tetrahedron is a contour face
Definition at line 146 of file Tetrahedron.h.
References _node0, _node2, _node3, and nlphysics::Node::contour().
NLPHYSICS_API bool nlphysics::Tetrahedron::face2 (void) const inline
Method that check and return if the 2 face of the tetrahedron is a contour face.
Returns
true if the 2 face of the tetrahedron is a contour face
Definition at line 157 of file Tetrahedron.h.
References _node0, _node1, _node3, and nlphysics::Node::contour().
NLPHYSICS_API bool nlphysics::Tetrahedron::face3 (void) const inline
Method that check and return if the 3 face of the tetrahedron is a contour face.
Returns
true if the 3 face of the tetrahedron is a contour face
Definition at line 168 of file Tetrahedron.h.
References _node1, _node2, _node3, and nlphysics::Node::contour().
NLPHYSICS_API NodePtr& nlphysics::Tetrahedron::node0 (void) inline
Method that returns the first tetrahedron node.
Returns
the first tetrahedron node
Definition at line 71 of file Tetrahedron.h.
References _node0.
NLPHYSICS_API NodePtr& nlphysics::Tetrahedron::node1 (void) inline
Method that returns the second tetrahedron node.
Returns
the second tetrahedron node
Definition at line 78 of file Tetrahedron.h.
References _node1.
NLPHYSICS_API NodePtr& nlphysics::Tetrahedron::node2 (void) inline
Method that returns the third tetrahedron node.
Returns
the third tetrahedron node
Definition at line 85 of file Tetrahedron.h.
References _node2.
NLPHYSICS_API NodePtr& nlphysics::Tetrahedron::node3 (void) inline
Method that returns the fourth tetrahedron node.
Returns
the fourth tetrahedron node
Definition at line 92 of file Tetrahedron.h.
References _node3.
NLPHYSICS_API float& nlphysics::Tetrahedron::volume (void) inline
Method that returns the tetrahedron volume.
Returns
the tetrahedron volume
Definition at line 127 of file Tetrahedron.h.
References _volume.
The documentation for this class was generated from the following file:
Tetrahedron.h