neurolots: nlphysics::Node Class Reference
nlphysics::Node Class Reference
Public Member Functions
NLPHYSICS_API Node (const Eigen::Vector3f &initialPosition_, unsigned int id_=0, bool contour_=false)
Constructor.
NLPHYSICS_API ~Node (void)
Default destructor.
NLPHYSICS_API unsigned int & id (void)
Method that returns the node id.
NLPHYSICS_API unsigned int id (void) const
NLPHYSICS_API Eigen::Vector3f & initialPosition (void)
Method that returns the node initial position.
NLPHYSICS_API const Eigen::Vector3f & initialPosition (void) const
NLPHYSICS_API Eigen::Vector3f & displacement (void)
Method that returns the node displacement.
NLPHYSICS_API const Eigen::Vector3f & displacement (void) const
NLPHYSICS_API Eigen::Vector3f & position (void)
Method that returns the node position.
NLPHYSICS_API const Eigen::Vector3f & position (void) const
NLPHYSICS_API Eigen::Vector3f & center (void)
Method that returns the node center.
NLPHYSICS_API const Eigen::Vector3f & center (void) const
NLPHYSICS_API Eigen::Vector3f & tangent (void)
Method that returns the node tangent.
NLPHYSICS_API const Eigen::Vector3f & tangent (void) const
NLPHYSICS_API Eigen::Vector3f & force (void)
Method that returns the node force.
NLPHYSICS_API const Eigen::Vector3f & force (void) const
NLPHYSICS_API bool & fixed (void)
Method that returns the node fixed condition.
NLPHYSICS_API bool fixed (void) const
NLPHYSICS_API bool & contour (void)
Method that returns the node contour condition.
NLPHYSICS_API bool contour (void) const
Protected Attributes
unsigned int _id
Index.
Eigen::Vector3f _initialPosition
Initial position.
Eigen::Vector3f _displacement
Displacement.
Eigen::Vector3f _position
Actual position.
Eigen::Vector3f _center
Node center.
Eigen::Vector3f _tangent
Node tangetn.
Eigen::Vector3f _force
Force.
bool _fixed
Condition if node is fixed or not.
bool _contour
Condition that indicates if the node is a inner node or a contr.
Detailed Description
Definition at line 40 of file Node.h.
Constructor & Destructor Documentation
NLPHYSICS_API nlphysics::Node::Node (const Eigen::Vector3f & initialPosition_, unsigned int id_ = 0, bool contour_ = false) inline
Constructor.
Parameters
intialPosition_ vector with the initial position
id_ node index
contour_ condition of inner or contour node
Definition at line 52 of file Node.h.
Member Function Documentation
NLPHYSICS_API Eigen::Vector3f& nlphysics::Node::center (void) inline
Method that returns the node center.
Returns
the node center
Definition at line 119 of file Node.h.
References _center.
NLPHYSICS_API bool& nlphysics::Node::contour (void) inline
Method that returns the node contour condition.
Returns
the node contour condition
Definition at line 159 of file Node.h.
References _contour.
Referenced by nlphysics::Tetrahedron::face0(), nlphysics::Tetrahedron::face1(), nlphysics::Tetrahedron::face2(), and nlphysics::Tetrahedron::face3().
NLPHYSICS_API Eigen::Vector3f& nlphysics::Node::displacement (void) inline
Method that returns the node displacement.
Returns
the node displacement
Definition at line 99 of file Node.h.
References _displacement.
NLPHYSICS_API bool& nlphysics::Node::fixed (void) inline
Method that returns the node fixed condition.
Returns
the node fixed condition
Definition at line 149 of file Node.h.
References _fixed.
NLPHYSICS_API Eigen::Vector3f& nlphysics::Node::force (void) inline
Method that returns the node force.
Returns
the node force
Definition at line 139 of file Node.h.
References _force.
NLPHYSICS_API unsigned int& nlphysics::Node::id (void) inline
Method that returns the node id.
Returns
the node id
Definition at line 78 of file Node.h.
References _id.
NLPHYSICS_API Eigen::Vector3f& nlphysics::Node::initialPosition (void) inline
Method that returns the node initial position.
Returns
the node initial position
Definition at line 88 of file Node.h.
References _initialPosition.
NLPHYSICS_API Eigen::Vector3f& nlphysics::Node::position (void) inline
Method that returns the node position.
Returns
the node position
Definition at line 109 of file Node.h.
References _position.
NLPHYSICS_API Eigen::Vector3f& nlphysics::Node::tangent (void) inline
Method that returns the node tangent.
Returns
the node tangent
Definition at line 129 of file Node.h.
References _tangent.
The documentation for this class was generated from the following file:
Node.h