set(NEUROLOTS_MATURITY "EP")
set(NEUROLOTS_DESCRIPTION "NeuroLOTs")
set(NEUROLOTS_GIT_ROOT_URL "https://gitlab-ci-token:r9A_my_A-tH7boDGXe2A@gitlab.vg-lab.es/nsviz/neurolots.git")
set(NEUROLOTS_PACKAGE_URL "")
set(NEUROLOTS_CI_URL "")
set(NEUROLOTS_CI_PNG "")
set(NEUROLOTS_ISSUES_URL "")
