nsol: nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES > Class Template Reference
nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES > Class Template Reference
Public Member Functions
MorphologyPtr loadMorphology (const std::vector< float > &points_, const std::vector< unsigned int > &segments_)
Creates a generic morphology using a vector of points and segments.
Protected Member Functions
void _groupSections (const SectionPtr section_, std::set< SectionPtr > &uniqueSections_)
Detailed Description
template<VECTORS_READER_TEMPLATE_CLASSES>
class nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES >
Definition at line 44 of file VectorsReader.h.
Member Function Documentation
template<VECTORS_READER_TEMPLATE_CLASSES > MorphologyPtr nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES >::loadMorphology (const std::vector< float > & points_, const std::vector< unsigned int > & segments_)
Creates a generic morphology using a vector of points and segments.
Parameters
points_ each point or node is represented by four floats (position {x,y,z} and radius).
segments_ each segment is represented by two unsigned integers (indices of the two nodes belonging to the segment). Indices must have values from 0 to (#points-1).
Returns
MorphologyPtr a generic morphology.
Definition at line 76 of file VectorsReader.h.
References nsol::Section::addBackwardNode(), nsol::Section::addForwardNode(), nsol::Section::backwardNeighbors(), and nsol::Section::forwardNeighbors().
The documentation for this class was generated from the following file:
VectorsReader.h