nsol: nsol::Section Class Reference
nsol::Section Class Reference
Public Member Functions
Section (void)
Default constructor.
virtual ~Section ()
Default destructor.
Sections & backwardNeighbors (void)
Gets the backward neighbour sections of this section.
const Sections & backwardNeighbors (void) const
Sections & forwardNeighbors (void)
Gets the forward neighbour sections of this section.
const Sections & forwardNeighbors (void) const
void addBackwardNeighbour (SectionPtr section)
Adds backward neighbour section to this section.
void addForwardNeighbour (SectionPtr section)
Adds forward neighbour section to this section.
bool deleteBackwardNeighbour (SectionPtr section_)
Delete backward neighbour section from this section.
bool deleteForwardNeighbour (SectionPtr section_)
Delete forward neighbour section from this section.
void addNeighbour (SectionPtr section, NodePtr node)
Check if the node connects with the backward or the fordward neighbour sections and add the section to the correspondent sections container.
Nodes & nodes (void)
Return the middle Nodes.
const Nodes & nodes (void) const
virtual void addBackwardNode (NodePtr node)
Adds a node at the start of this section.
virtual void addForwardNode (NodePtr node)
Adds a node at the end of this section.
NodePtr backwardNode (void)
Gets the first Node of the Section.
NodePtr forwardNode (void)
Gets the last Node of the Section.
virtual SectionPtr clone (void) const
bool operator== (Section &other) const
bool operator!= (Section &other) const
virtual SectionPtr asSection (void)
Public Member Functions inherited from nsol::Object
virtual ColumnPtr asColumn (void)
virtual MiniColumnPtr asMiniColumn (void)
virtual NeuronPtr asNeuron (void)
virtual NeuronMorphologyPtr asNeuronMorphology (void)
virtual NodePtr asNode (void)
virtual ObjectWithProperties * properties (void)
virtual ObjectPtr create (void)
Protected Attributes
Nodes _nodes
Container of the middle nodes of this section.
Sections _backwardSections
Container of the backward neighbour sections of this section.
Sections _forwardSections
Container of the forward neighbour sections of this section.
Detailed Description
Definition at line 34 of file Section.h.
Member Function Documentation
void nsol::Section::addBackwardNeighbour (SectionPtr section)
Adds backward neighbour section to this section.
Parameters
section pointer to the section to be added
virtual void nsol::Section::addBackwardNode (NodePtr node) virtual
Adds a node at the start of this section.
Parameters
node pointer to the Node to add. Precondition: pointer is not null.
Referenced by nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES >::loadMorphology().
void nsol::Section::addForwardNeighbour (SectionPtr section)
Adds forward neighbour section to this section.
Parameters
section pointer to the section to be added
virtual void nsol::Section::addForwardNode (NodePtr node) virtual
Adds a node at the end of this section.
Parameters
node pointer to the Node to add. Precondition: pointer is not null.
Referenced by nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES >::loadMorphology().
void nsol::Section::addNeighbour (SectionPtr section, NodePtr node)
Check if the node connects with the backward or the fordward neighbour sections and add the section to the correspondent sections container.
Parameters
section pointer to the section to be added
node pointer to the node between sections
Sections& nsol::Section::backwardNeighbors (void)
Gets the backward neighbour sections of this section.
Returns
container of the backward neighbour sections
Referenced by nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES >::loadMorphology().
NodePtr nsol::Section::backwardNode (void)
Gets the first Node of the Section.
Returns
pointer to the first Node, null in case it doesn't have any
bool nsol::Section::deleteBackwardNeighbour (SectionPtr section_)
Delete backward neighbour section from this section.
Parameters
section pointer to the section to be deleted
Returns
true if the given section is in the backward sections
bool nsol::Section::deleteForwardNeighbour (SectionPtr section_)
Delete forward neighbour section from this section.
Parameters
section pointer to the section to be deleted
Returns
true if the given section is in the forward sections
Sections& nsol::Section::forwardNeighbors (void)
Gets the forward neighbour sections of this section.
Returns
container of the forward neighbour sections
Referenced by nsol::VectorsReaderTemplated< VECTORS_READER_TEMPLATE_CLASSES >::loadMorphology().
NodePtr nsol::Section::forwardNode (void)
Gets the last Node of the Section.
Returns
pointer to the first Node, null in case it doesn't have any
Nodes& nsol::Section::nodes (void)
Return the middle Nodes.
Returns
container of middle Nodes
The documentation for this class was generated from the following file:
Section.h