nsol: nsol::Soma Class Reference
nsol::Soma Class Reference
Class to represent the soma of neurons.
#include <Soma.h>
Public Member Functions
Soma (void)
Default constructor.
virtual ~Soma (void)
Destructor.
Vec3f center (void) const
Method to get the center of the soma.
Nodes & nodes (void)
Method to get the container of nodes.
const float & maxRadius (void) const
Method to get the max radius of the soma.
const float & minRadius (void) const
Method to get the min radius of the soma.
const float & meanRadius (void) const
Method to get the mean radius of the soma.
void center (const Vec3f &center_)
Method to set the center of the soma.
void addNode (NodePtr node)
Method to add a node to the soma.
virtual const SomaStats * stats (void) const
virtual SomaPtr clone (void) const
bool operator== (Soma &other)
bool operator!= (Soma &other)
Protected Attributes
Vec3f _center
Center of the soma.
Nodes _nodes
Container of nodes of the soma.
float _maxRadius
Maximum radius of the soma.
float _minRadius
Minimum radius of the soma.
float _meanRadius
Mean radius of the soma.
Detailed Description
Class to represent the soma of neurons.
This class represents the soma and holds a container of the nodes that have been traced of its contour
Definition at line 38 of file Soma.h.
Member Function Documentation
void nsol::Soma::addNode (NodePtr node)
Method to add a node to the soma.
Parameters
node pointer to the node to add
Referenced by nsol::AscReaderTemplated< ASC_READER_TEMPLATE_CLASSES >::_ReadSoma(), and nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::readMorphology().
Vec3f nsol::Soma::center (void) const
Method to get the center of the soma.
Returns
center of the soma
Referenced by nsol::AscReaderTemplated< ASC_READER_TEMPLATE_CLASSES >::readMorphology(), and nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::readMorphology().
void nsol::Soma::center (const Vec3f & center_)
Method to set the center of the soma.
Parameters
center_ New center of the soma
const float& nsol::Soma::maxRadius (void) const
Method to get the max radius of the soma.
Returns
max radius of the soma
const float& nsol::Soma::meanRadius (void) const
Method to get the mean radius of the soma.
Returns
mean radius of the soma
const float& nsol::Soma::minRadius (void) const
Method to get the min radius of the soma.
Returns
min radius of the soma
Nodes& nsol::Soma::nodes (void)
Method to get the container of nodes.
Returns
container with all the nodes of the soma
The documentation for this class was generated from the following file:
Soma.h