nsol: nsol::Column Class Reference
nsol::Column Class Reference
A class to represent columns.
#include <Column.h>
Public Member Functions
unsigned int numberOfNeurons (const bool all=true, const Neuron::TMorphologicalType neuronType=Neuron::PYRAMIDAL, const unsigned int layer=0) const
Method to get the number of neurons in the column.
virtual ColumnPtr asColumn (void)
Constructors and destructors
Column (unsigned short id=0)
Default constructor.
Column (const Column &other)
Copy constructor.
virtual ~Column (void)
Default destructur.
virtual ColumnStats * stats (void)
Returns object as MiniColumnStats.
Id related methods
unsigned short & id (void)
Method to get-set the column id.
unsigned short id (void) const
Method to get the column id.
MiniColumn related methods
void addMiniColumn (MiniColumnPtr miniColumn)
Method to add a mini column.
bool removeMiniColumn (MiniColumnPtr miniColumn)
Method to remove a mini column.
void clearMiniColumns (void)
Method to clear mini columns.
MiniColumns & miniColumns (void)
Method to get minicolumns.
MiniColumns miniColumns (void) const
Method to get minicolumns as const.
unsigned int numberOfMiniColumns (void) const
Method to get the number of minicolumns.
Operators
Column & operator= (const Column &other)
bool operator== (Column &other) const
bool operator!= (Column &other) const
Public Member Functions inherited from nsol::Object
virtual MiniColumnPtr asMiniColumn (void)
virtual NeuronPtr asNeuron (void)
virtual NeuronMorphologyPtr asNeuronMorphology (void)
virtual SectionPtr asSection (void)
virtual NodePtr asNode (void)
virtual ObjectWithProperties * properties (void)
virtual ObjectPtr create (void)
Protected Attributes
unsigned short _id
Identifier of the column.
MiniColumns _miniColumns
Container of minicolumns.
Detailed Description
A class to represent columns.
Columns provides pointers to minicolumns and methods for different morphological values computation.
Definition at line 42 of file Column.h.
Constructor & Destructor Documentation
nsol::Column::Column (unsigned short id = 0)
Default constructor.
Parameters
id id of the column.
nsol::Column::Column (const Column & other)
Copy constructor.
Parameters
other column to be copied
Member Function Documentation
void nsol::Column::addMiniColumn (MiniColumnPtr miniColumn)
Method to add a mini column.
Parameters
miniColumn minicolumn to add to this column
Referenced by nsol::XmlSceneReader::loadXml(), and stats().
unsigned short& nsol::Column::id (void)
Method to get-set the column id.
Returns
column id
Referenced by stats().
unsigned short nsol::Column::id (void) const
Method to get the column id.
Returns
reference to column id
MiniColumns& nsol::Column::miniColumns (void)
Method to get minicolumns.
Returns
minicolumns of the column
Referenced by stats().
MiniColumns nsol::Column::miniColumns (void) const
Method to get minicolumns as const.
Returns
minicolumns of the column
unsigned int nsol::Column::numberOfMiniColumns (void) const
Method to get the number of minicolumns.
Returns
numbers of minicolumns
Referenced by stats().
unsigned int nsol::Column::numberOfNeurons (const bool all = true, const Neuron::TMorphologicalType neuronType = Neuron::PYRAMIDAL, const unsigned int layer = 0) const
Method to get the number of neurons in the column.
Parameters
all if this is true all neurons are counted
neuronType if "all" is false neurons of the passed type will be counted
layer if "all" is false neurons of the layer will be counted. If later is 0 then all neurons of all layers will be counted.
Returns
number of neurons that match the criteria
Referenced by stats().
bool nsol::Column::removeMiniColumn (MiniColumnPtr miniColumn)
Method to remove a mini column.
Parameters
miniColumn pointer to the minicolumn to be removed
Returns
true if minicolumn removed false otherwise
Referenced by stats().
virtual ColumnStats* nsol::Column::stats (void) inline virtual
Returns object as MiniColumnStats.
Returns
pointer to MiniColumnStats object
Reimplemented in nsol::ColumnStats.
Definition at line 76 of file Column.h.
References addMiniColumn(), clearMiniColumns(), id(), miniColumns(), numberOfMiniColumns(), numberOfNeurons(), nsol::Neuron::PYRAMIDAL, and removeMiniColumn().
The documentation for this class was generated from the following file:
Column.h