nsol: nsol::Log Class Reference
nsol::Log Class Reference
Static class to log output.
#include <Log.h>
Static Public Member Functions
static void setLogLevel (const TLogLevel logLevel)
Set current log level.
static TLogLevel logLevel (void)
Get current log level.
static void setStream (std::ostream &stream)
Set current output stream.
static const std::ostream & stream (void)
Get current output stream.
static void log (const std::string &msg, const TLogLevel level=LOG_LEVEL_VERBOSE)
Method to log out a message in a specific level.
static void log (const std::string &msg, std::ostream &stream, const TLogLevel level=LOG_LEVEL_VERBOSE)
Method to log out a message in a specific level to a specific stream.
static TLogLevel stringToLogLevel (std::string logLevelString)
Static Protected Attributes
static TLogLevel _logLevel
Current log level. This can be overwritten with proper value assigned to environment variable NSOL_LOG_LEVEL.
static std::ostream * _stream
Current stream to write log to.
Detailed Description
Static class to log output.
Definition at line 44 of file Log.h.
Member Function Documentation
static void nsol::Log::log (const std::string & msg, const TLogLevel level = LOG_LEVEL_VERBOSE) static
Method to log out a message in a specific level.
Parameters
msg message to log
level level of the message
Referenced by nsol::AscReaderTemplated< ASC_READER_TEMPLATE_CLASSES >::_ReadNeurite(), nsol::XmlSceneReader::loadXml(), nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::readMorphology(), and nsol::AscReaderTemplated< ASC_READER_TEMPLATE_CLASSES >::readMorphology().
static void nsol::Log::log (const std::string & msg, std::ostream & stream, const TLogLevel level = LOG_LEVEL_VERBOSE) static
Method to log out a message in a specific level to a specific stream.
Parameters
msg message to log
level level of the message
stream stream where log will be written
static TLogLevel nsol::Log::logLevel (void) static
Get current log level.
Returns
current log level
static void nsol::Log::setLogLevel (const TLogLevel logLevel) static
Set current log level.
Parameters
logLevel level to be set
static void nsol::Log::setStream (std::ostream & stream) static
Set current output stream.
Parameters
stream output stream to be set
static const std::ostream& nsol::Log::stream (void) static
Get current output stream.
Returns
current output stream
The documentation for this class was generated from the following file:
Log.h