nsol: nsol::NeuronMorphologySection Class Reference
nsol::NeuronMorphologySection Class Reference
Public Member Functions
NeuronMorphologySection (void)
Default constructor.
virtual ~NeuronMorphologySection ()
Default destructor.
unsigned int id (void)
Method to get the gid of the neuron morphology section.
void id (unsigned int id_)
Method to set the gid of the neuron morphology section.
NeuritePtr neurite (void)
Gets the parent Neurite of the Neuron Morphology Section.
void neurite (NeuritePtr neurite_)
Sets the parent neurite of this Neuron Morphology Section.
SectionPtr parent (void)
Gets the parent Section of this Section.
void parent (SectionPtr parent_)
Sets the parent Section of this Section.
void addChild (SectionPtr section_)
Adds child Section to this Section.
Sections & children (void)
Return the children sections.
const Sections & children (void) const
virtual void addNode (NodePtr node_)
Adds a Node at the end of Section.
NodePtr firstNode (void)
Gets the first Node of the Section.
virtual void firstNode (NodePtr firstNode_)
Sets first Node of the Section.
NodePtr lastNode (void)
Gets the last Node of the Section.
virtual NeuronMorphologySectionStats * stats (void)
Returns object as SectionStats.
virtual SectionPtr clone (void) const
virtual SectionPtr asNeuronMorphologySection (void)
Public Member Functions inherited from nsol::Section
Section (void)
Default constructor.
virtual ~Section ()
Default destructor.
Sections & backwardNeighbors (void)
Gets the backward neighbour sections of this section.
const Sections & backwardNeighbors (void) const
Sections & forwardNeighbors (void)
Gets the forward neighbour sections of this section.
const Sections & forwardNeighbors (void) const
void addBackwardNeighbour (SectionPtr section_)
Adds backward neighbour section to this section.
void addForwardNeighbour (SectionPtr section_)
Adds forward neighbour section to this section.
void addNeighbour (SectionPtr section_, NodePtr node_)
Check if the node connects with the backward or the fordward neighbour sections and add the section to the correspondent sections container.
Nodes & nodes (void)
Return the middle Nodes.
const Nodes & nodes (void) const
virtual void addBackwardNode (NodePtr node)
Adds a node at the start of this section.
virtual void addForwardNode (NodePtr node)
Adds a node at the end of this section.
NodePtr backwardNode (void)
Gets the first Node of the Section.
NodePtr forwardNode (void)
Gets the last Node of the Section.
bool operator== (Section &other) const
bool operator!= (Section &other) const
virtual SectionPtr asSection (void)
Public Member Functions inherited from nsol::Object
virtual ColumnPtr asColumn (void)
virtual MiniColumnPtr asMiniColumn (void)
virtual NeuronPtr asNeuron (void)
virtual NeuronMorphologyPtr asNeuronMorphology (void)
virtual NodePtr asNode (void)
virtual ObjectWithProperties * properties (void)
virtual ObjectPtr create (void)
Protected Attributes
unsigned int _id
Unique id.
NeuritePtr _neurite
Parent neurite of the section.
Protected Attributes inherited from nsol::Section
Nodes _nodes
Container of the middle nodes of this section.
Sections _backwardSections
Container of the backward neighbour sections of this section.
Sections _forwardSections
Container of the forward neighbour sections of this section.
Detailed Description
Definition at line 33 of file NeuronMorphologySection.h.
Member Function Documentation
void nsol::NeuronMorphologySection::addChild (SectionPtr section_)
Adds child Section to this Section.
Parameters
section pointer to the section to be added
Referenced by nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::_ReadNeurite().
virtual void nsol::NeuronMorphologySection::addNode (NodePtr node_) virtual
Adds a Node at the end of Section.
Parameters
Node pointer to the Node to add. Precondition: pointer is not null.
Reimplemented in nsol::NeuronMorphologySectionCachedStats.
Referenced by nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::_ReadNeurite(), and nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::_ReadSection().
Sections& nsol::NeuronMorphologySection::children (void)
Return the children sections.
Returns
container of children sections
NodePtr nsol::NeuronMorphologySection::firstNode (void)
Gets the first Node of the Section.
Returns
pointer to the first Node, null in case it doesn't have any
Referenced by nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::_ReadNeurite().
virtual void nsol::NeuronMorphologySection::firstNode (NodePtr firstNode_) virtual
Sets first Node of the Section.
This method is virtual to allow reimplementation for cached objects and dirty state propagation
Parameters
firstNode pointer to the Node.
Reimplemented in nsol::NeuronMorphologySectionCachedStats.
unsigned int nsol::NeuronMorphologySection::id (void)
Method to get the gid of the neuron morphology section.
Returns
gid
void nsol::NeuronMorphologySection::id (unsigned int id_)
Method to set the gid of the neuron morphology section.
Parameters
gid
NodePtr nsol::NeuronMorphologySection::lastNode (void)
Gets the last Node of the Section.
Returns
pointer to the firts Node, null in case it doesn't have any
NeuritePtr nsol::NeuronMorphologySection::neurite (void)
Gets the parent Neurite of the Neuron Morphology Section.
Returns
pointer to the parent Neurite
Referenced by nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::_ReadNeurite().
void nsol::NeuronMorphologySection::neurite (NeuritePtr neurite_)
Sets the parent neurite of this Neuron Morphology Section.
Parameters
neurite pointer to parent neurite
SectionPtr nsol::NeuronMorphologySection::parent (void)
Gets the parent Section of this Section.
Returns
pointer to the parent Section
Referenced by nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::_ReadNeurite().
void nsol::NeuronMorphologySection::parent (SectionPtr parent_)
Sets the parent Section of this Section.
Parameters
parent pointer to parent Section
virtual NeuronMorphologySectionStats* nsol::NeuronMorphologySection::stats (void) virtual
Returns object as SectionStats.
Returns
pointer to SectionStats object
Reimplemented in nsol::NeuronMorphologySectionStats.
The documentation for this class was generated from the following file:
NeuronMorphologySection.h