nsol: nsol::NeuronMorphology Class Reference
nsol::NeuronMorphology Class Reference
A class to represent morphology of neurons.
#include <NeuronMorphology.h>
Public Member Functions
NeuronMorphology (void)
Default Neuron class constructor.
NeuronMorphology (SomaPtr soma)
SomaPtr soma (SomaPtr soma)
Method to set the neuronal soma.
NeuritePtr addNeurite (NeuritePtr neurite)
Method to add a new neurite to the neuron.
Dendrites * dendrites (void) const
Method to get all the dendrites in a container.
Dendrites * basalDendrites (void) const
Method to get all the basal dendrites in a container.
Dendrites * apicalDendrites (void) const
Method to get all the apical dendrites in a container.
DendritePtr apicalDendrite (void) const
Method to get the first apical dendrite.
AxonPtr axon (void) const
Returns axon if exists.
virtual Neurites & neurites (void)
const Neurites & neurites (void) const
virtual Neurons & parentNeurons (void)
const Neurons & parentNeurons (void) const
SomaPtr soma (void)
virtual NeuronMorphologyStats * stats (void)
void addParentNeuron (NeuronPtr neuron)
virtual NeuronMorphologyPtr asNeuronMorphology (void)
virtual NeuronMorphologyPtr clone (void) const
bool operator== (NeuronMorphology &other)
bool operator!= (NeuronMorphology &other)
Public Member Functions inherited from nsol::Morphology
Sections & sections (void)
Public Member Functions inherited from nsol::Object
virtual ColumnPtr asColumn (void)
virtual MiniColumnPtr asMiniColumn (void)
virtual NeuronPtr asNeuron (void)
virtual SectionPtr asSection (void)
virtual NodePtr asNode (void)
virtual ObjectWithProperties * properties (void)
virtual ObjectPtr create (void)
Protected Attributes
SomaPtr _soma
Neurites _neurites
Neurons _parentNeurons
Protected Attributes inherited from nsol::Morphology
Sections _sections
Morphology sections.
Detailed Description
A class to represent morphology of neurons.
TODO: extend long description
Definition at line 49 of file NeuronMorphology.h.
Constructor & Destructor Documentation
nsol::NeuronMorphology::NeuronMorphology (void)
Default Neuron class constructor.
TODO: construct protected objects
Member Function Documentation
NeuritePtr nsol::NeuronMorphology::addNeurite (NeuritePtr neurite)
Method to add a new neurite to the neuron.
Parameters
neurite pointer to the neurite to be added.
Returns
pointer to the added neurite
Referenced by nsol::AscReaderTemplated< ASC_READER_TEMPLATE_CLASSES >::readMorphology(), and nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::readMorphology().
DendritePtr nsol::NeuronMorphology::apicalDendrite (void) const
Method to get the first apical dendrite.
Returns
pointer to the apical dendrite. nullptr in case not found.
Dendrites* nsol::NeuronMorphology::apicalDendrites (void) const
Method to get all the apical dendrites in a container.
Memory for the container is allocated.
Returns
pointer to the container of Dendrites
AxonPtr nsol::NeuronMorphology::axon (void) const
Returns axon if exists.
Returns
pointer to the axon or nullptr in case it doens't exist
Dendrites* nsol::NeuronMorphology::basalDendrites (void) const
Method to get all the basal dendrites in a container.
Memory for the container is allocated.
Returns
pointer to the container of Dendrites
Dendrites* nsol::NeuronMorphology::dendrites (void) const
Method to get all the dendrites in a container.
Memory for the container is allocated.
Returns
pointer to the container of Dendrites
SomaPtr nsol::NeuronMorphology::soma (SomaPtr soma)
Method to set the neuronal soma.
Parameters
soma pointer to the soma to be setted.
Returns
pointer to the setted soma
Referenced by nsol::AscReaderTemplated< ASC_READER_TEMPLATE_CLASSES >::_ReadSoma(), nsol::SwcReaderTemplated< SWC_READER_TEMPLATE_CLASSES >::readMorphology(), and nsol::AscReaderTemplated< ASC_READER_TEMPLATE_CLASSES >::readMorphology().
The documentation for this class was generated from the following file:
NeuronMorphology.h