nsol: nsol::XmlSceneReader Class Reference
nsol::XmlSceneReader Class Reference
#include <XmlSceneReader.h>
Static Public Member Functions
template<class NODE = Node, class SECTION = Section, class DENDRITE = Dendrite, class AXON = Axon, class SOMA = Soma, class NEURONMORPHOLOGY = NeuronMorphology, class NEURON = Neuron, class MINICOLUMN = MiniColumn, class COLUMN = Column>
static void loadXml (const std::string &xmlSceneFile, Columns &, NeuronsMap &, std::map< std::string, NeuronMorphologyPtr > &)
Read structure and optionally morphologies to xml file.
Detailed Description
This class allows to read the structure morphologies of a given Xml file.
Definition at line 44 of file XmlSceneReader.h.
Member Function Documentation
template<class NODE = Node, class SECTION = Section, class DENDRITE = Dendrite, class AXON = Axon, class SOMA = Soma, class NEURONMORPHOLOGY = NeuronMorphology, class NEURON = Neuron, class MINICOLUMN = MiniColumn, class COLUMN = Column> static void nsol::XmlSceneReader::loadXml (const std::string & xmlSceneFile, Columns & , NeuronsMap & , std::map< std::string, NeuronMorphologyPtr > &) inline static
Read structure and optionally morphologies to xml file.
Parameters
xmlSceneFile intput filename to read
Definition at line 83 of file XmlSceneReader.h.
References nsol::Column::addMiniColumn(), nsol::MiniColumn::addNeuron(), nsol::Neuron::INTERNEURON, nsol::Log::log(), nsol::Neuron::PYRAMIDAL, and nsol::Neuron::UNDEFINED.
The documentation for this class was generated from the following file:
XmlSceneReader.h