set(NSOL_MATURITY "EP")
set(NSOL_DESCRIPTION "Nsol - Neuroscience Objects Library")
set(NSOL_GIT_ROOT_URL "https://gitlab-ci-token:B3UJxVTWs1pA8UF-aMrv@gitlab.gmrv.es/nsviz/nsol.git")
set(NSOL_PACKAGE_URL "")
set(NSOL_CI_URL "")
set(NSOL_CI_PNG "")
set(NSOL_ISSUES_URL "")
