ReTo: reto::Camera Class Reference
reto::Camera Class Reference
Class to manage camera.
#include <Camera.h>
Public Member Functions
Camera (float fov_=45.0f, float ratio_=((float) 16)/9, float nearPlane_=0.1f, float farPlane_=10000.0f, Eigen::Vector3f pivot_=Eigen::Vector3f(0.0f, 0.0f, 0.0f), float radius_=1000.0f, float yaw_=0.0f, float pitch_=0.0f)
Camera constructor.
~Camera (void)
Default destructor.
void localTranslation (Eigen::Vector3f increment_)
Method to translate the camera from the actual position.
void localRotation (const float yaw_, const float pitch_)
Method to rotate the camera from the actual rotation.
bool anim (void)
Method to if there is a target pivot move the camera to this target pivot.
float fov (void)
Method to get the field of view of the camera.
float & farPlane (void)
Method to get and set the far plane of the camera.
Eigen::Vector3f pivot (void)
Method to get the actual pivot pin of the camera.
float radius (void)
Method to get the actual distance between the camera and the pivot pin aka camera radius.
float * projectionMatrix (void)
Method to get the pointer to projection matrix of the camera vectorized in columns.
float * orthoMatrix (void)
Method to get the pointer to ortho-projection matrix of the camera vectorized in columns.
float * viewMatrix (void)
Method to get the pointer to view matrix of the camera vectorized in columns.
float * viewProjectionMatrix (void)
Method to get the pointer to projectionview matrix of the camera vectorized in columns.
float * position (void)
Method to get the pointer to the camera position vectorized.
void ratio (float ratio_)
Method to set the camera projection ratio.
void pivot (Eigen::Vector3f pivot_)
Method to set the camera pivot pin.
void radius (const float radius_)
Method to set the distance between the camera and the pivot pin.
void rotation (const float yaw_, const float pitch_)
Method to set the rotation of the camera.
void targetPivot (Eigen::Vector3f targetPivot_)
Method to set the target pivot of the camera.
void targetRadius (const float targetRadius_)
Method to set the target camera distance between the camera and the pivot pin.
void targetPivotRadius (Eigen::Vector3f targetPivot_, const float targetRadius_)
Method to set the target pivot pin a nd the target camera distance between the camera and this pivot pin.
void animDuration (const float animDuration_)
Method to set the anim duration of the camera movement from actual pivot and radius to the target pivot and radius.
void setWindowSize (const int width_, const int height_)
Method to set window size.
int width (void)
Method to get window width size.
int height (void)
Method to get window height size.
Detailed Description
Class to manage camera.
This class manage the camera: allows to move, rotate, make zoom, anim and automatically synchronize the camera with other applications using of ZeroEQ
Definition at line 61 of file Camera.h.
Constructor & Destructor Documentation
reto::Camera::Camera (float fov_ = 45.0f, float ratio_ = ((float) 16)/9, float nearPlane_ = 0.1f, float farPlane_ = 10000.0f, Eigen::Vector3f pivot_ = Eigen::Vector3f(0.0f, 0.0f, 0.0f), float radius_ = 1000.0f, float yaw_ = 0.0f, float pitch_ = 0.0f)
Camera constructor.
Parameters
fov camera field of view
ratio camera ratio
nearPlane camera near plane
farPlan camera far plane
pivot camera rotation pivot
radius camera distance from the camera pivot
yaw camera rotation of y exe
pitch camera rotation of x exe
Member Function Documentation
bool reto::Camera::anim (void)
Method to if there is a target pivot move the camera to this target pivot.
Returns
boolean that is 1 if the camera is actually moving
float& reto::Camera::farPlane (void) inline
Method to get and set the far plane of the camera.
Returns
the reference to a float with the far plane attrib of the camera
Definition at line 144 of file Camera.h.
References animDuration(), height(), orthoMatrix(), pivot(), position(), projectionMatrix(), radius(), ratio(), rotation(), setWindowSize(), targetPivot(), targetPivotRadius(), targetRadius(), viewMatrix(), viewProjectionMatrix(), and width().
float reto::Camera::fov (void)
Method to get the field of view of the camera.
Returns
float with the field of view of the camera
int reto::Camera::height (void)
Method to get window height size.
Returns
window height size
Referenced by farPlane().
void reto::Camera::localRotation (const float yaw_, const float pitch_)
Method to rotate the camera from the actual rotation.
Parameters
yaw camera rotation of y exe
pitch camera rotation of x exe
void reto::Camera::localTranslation (Eigen::Vector3f increment_)
Method to translate the camera from the actual position.
Parameters
increment_ camera translation
float* reto::Camera::orthoMatrix (void)
Method to get the pointer to ortho-projection matrix of the camera vectorized in columns.
Returns
pointer to float whit the column vectorized ortho-projection matrix of the camera
Referenced by farPlane().
Eigen::Vector3f reto::Camera::pivot (void)
Method to get the actual pivot pin of the camera.
Returns
Eige::Vector3f with the pivot pin of the camera
Referenced by farPlane().
void reto::Camera::pivot (Eigen::Vector3f pivot_)
Method to set the camera pivot pin.
Parameters
pivot new camera pivot pin
float* reto::Camera::position (void)
Method to get the pointer to the camera position vectorized.
Returns
pointer to float whit the vectorized camera position
Referenced by farPlane().
float* reto::Camera::projectionMatrix (void)
Method to get the pointer to projection matrix of the camera vectorized in columns.
Returns
pointer to float whit the column vectorized projection matrix of the camera
Referenced by farPlane().
float reto::Camera::radius (void)
Method to get the actual distance between the camera and the pivot pin aka camera radius.
Returns
float with the distance between the camera and the pivot pin
Referenced by farPlane().
void reto::Camera::radius (const float radius_)
Method to set the distance between the camera and the pivot pin.
Parameters
radius distance between the camera and the pivot pin
void reto::Camera::ratio (float ratio_)
Method to set the camera projection ratio.
Parameters
ratio camera projection ratio
Referenced by farPlane().
void reto::Camera::rotation (const float yaw_, const float pitch_)
Method to set the rotation of the camera.
Parameters
yaw camera rotation of y exe
pitch camera rotation of x exe
Referenced by farPlane().
void reto::Camera::setWindowSize (const int width_, const int height_)
Method to set window size.
Parameters
w Window width
h Window height
Referenced by farPlane().
void reto::Camera::targetPivot (Eigen::Vector3f targetPivot_)
Method to set the target pivot of the camera.
Parameters
targetPivot camera target pivot pin
Referenced by farPlane().
void reto::Camera::targetPivotRadius (Eigen::Vector3f targetPivot_, const float targetRadius_)
Method to set the target pivot pin a nd the target camera distance between the camera and this pivot pin.
Parameters
targetPivot camera target pivot pin
targetRadius target camera distance between the camera and the pivot pin
Referenced by farPlane().
void reto::Camera::targetRadius (const float targetRadius_)
Method to set the target camera distance between the camera and the pivot pin.
Parameters
targetRadius target camera distance between the camera and the pivot pin
Referenced by farPlane().
float* reto::Camera::viewMatrix (void)
Method to get the pointer to view matrix of the camera vectorized in columns.
Returns
pointer to float whit the column vectorized view matrix of the camera
Referenced by farPlane().
float* reto::Camera::viewProjectionMatrix (void)
Method to get the pointer to projectionview matrix of the camera vectorized in columns.
Returns
pointer to float whit the column vectorized projectionview matrix of the camera
Referenced by farPlane().
int reto::Camera::width (void)
Method to get window width size.
Returns
window width size
Referenced by farPlane().
The documentation for this class was generated from the following file:
Camera.h